version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: spooky-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: spooky-quizz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spooky-quizz"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: spooky-network
